version: "3.4"

services:
  bottleshelf_api:
        depends_on:
          - nginx
        build:
          context: .
          dockerfile: dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=https://+:5001
          - ASPNETCORE_Kestrel__Certificates__Default__Password=password
          - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        expose:
          - "5000"
        restart: always
  nginx:
        container_name: nginx
        restart: always
        image: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf